spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  datasource:
    url: "jdbc:mysql://localhost/Team10"
    username: "root"
    password: "" # MySQL ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver