spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  datasource:
      url: jdbc:mysql://localhost/Team10
      username: root
      password: xjaqmffj
      driver-class-name: com.mysql.cj.jdbc.Driver